import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';

class PdfGenerator {
  static Future<File> generateReport({
    required String title,
    required Map<String, String> inputs,
    required Map<String, String> results,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 10),
              pw.Text('Date: ${DateTime.now().toLocal().toString().split(' ')[0]}'),
              pw.SizedBox(height: 20),
              
              pw.Text('Inputs:', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              _buildTable(inputs),
              
              pw.SizedBox(height: 20),
              pw.Text('Results:', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              _buildTable(results),
              
              pw.Spacer(),
              pw.Center(child: pw.Text('Generated by FINCALC PRO', style: const pw.TextStyle(color: PdfColors.grey))),
            ],
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File('${output.path}/report_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static pw.Widget _buildTable(Map<String, String> data) {
    return pw.Table.fromTextArray(
      context: null,
      data: <List<String>>[
        <String>['Parameter', 'Value'],
        ...data.entries.map((e) => [e.key, e.value]),
      ],
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
      cellHeight: 30,
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerRight,
      },
    );
  }
}
