import 'package:flutter/material.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Terms of Service')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Terms of Service', style: Theme.of(context).textTheme.headlineMedium),
            const SizedBox(height: 8),
            Text('Last updated: August 2026', style: Theme.of(context).textTheme.bodySmall),
            const SizedBox(height: 24),
            _section('Informational Purposes Only', 'The content and calculations provided by FeroCalc are for informational and educational purposes only. They do not constitute financial, investment, or legal advice.'),
            _section('No Guarantee of Accuracy', 'While we strive to provide accurate calculations, we make no guarantees regarding the accuracy, reliability, or completeness of any results generated by the app. Bank rates and financial rules may change without notice.'),
            _section('Use at Your Own Risk', 'Your use of FeroCalc is entirely at your own risk. You should verify all calculations and consult with a qualified financial advisor before making any financial decisions.'),
            _section('Estimates Only', 'All calculations provided by the app are estimates and should not be considered final or binding. Actual results may vary based on numerous factors not accounted for in these basic calculations.'),
            _section('Limitation of Liability', 'We shall not be held liable for any financial decisions, losses, or damages resulting from the use of this app or reliance on its calculations.'),
            _section('Modifications to Terms', 'We reserve the right to modify these terms at any time. Continued use of the app constitutes acceptance of any updated terms.'),
            _section('Contact Us', 'If you have questions about these Terms, please contact us at ferocalc.app@gmail.com'),
          ],
        ),
      ),
    );
  }

  Widget _section(String title, String body) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
          const SizedBox(height: 8),
          Text(body, style: const TextStyle(fontSize: 14, height: 1.6)),
        ],
      ),
    );
  }
}
